config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
    # appointment planning for students
    resources 'planner', only: [ :show ]

    # appointments overview for TA's
    resources 'live', only: [ :index ]
    resources 'appointments', param: 'uuid', only: [ :show ] do
        put 'complete'
        put 'claim'
        put 'cancel'
    end

    # change hours etc
    resources 'courses', only: [ :index, :new, :create, :edit, :update ] do
        resources 'appointments', only: [ :create ]
        post 'bulk', to: 'courses#bulk'
        resources 'year', param: 'number', only: [] do
            resources 'week', param: 'number', only: [] do
                resource 'schedule', only: [ :show, :edit, :update ]
            end
        end
        resources 'feeds', only: [ :show ], param: 'token'
    end

    post 'logout', to: 'users#logout'

    # welcome and bumper page
    namespace 'home' do
        get 'index'
        get 'register'
    end

    # user registration
    resources 'users', only: [ :new, :create ]

    root to: "home#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :require_admin

    def index
        @courses = Course.all
    end

    def new
        @course = Course.new
    end

    def create
        course = Course.create! course_params
        redirect_to edit_course_path(course)
    end

    def edit
        @course = Course.find params[:id]
        @coming_weeks = @course.schedules.for_coming_weeks
    end

    def update
        course = Course.find params[:id]
        course.update(course_params)
        redirect_to edit_course_path(course)
    end

    def bulk
        course = Course.find params[:course_id]
        slots = {}

        for day in 0..6 do
            day_slots = {}
            for hour in 9..17 do
                amount = params[day.to_s + "-" + hour.to_s].to_i
                day_slots[hour] = amount unless amount == 0
            end
            slots[day] = day_slots
        end

        for week in params[:start].to_i..params[:end].to_i do
            schedule = Schedule.find_or_create_by(course: course, week: week, year: Date.current.year)
            schedule.slots = slots
            schedule.save!
        end

        redirect_to edit_course_path(course)
    end

    def course_params
        params.require(:course).permit(:name, :slots, :minimum, :location)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/bulk.html.erb
<h1>Courses#bulk</h1>
<p>Find me in app/views/courses/bulk.html.erb</p>

app/views/courses/create.html.erb
<h1>Courses#create</h1>
<p>Find me in app/views/courses/create.html.erb</p>

app/views/courses/edit.html.erb
<div class="row justify-content-center">
    <div class="col-lg-6">
        <h3 class="text-center"><%= @course.name %></h3>
    </div>
</div>

<div class="row justify-content-center pb-5">
    <div class="col-lg-6">
        <%= form_for [@course] do |form| %>
            <div class="form-floating mt-4">
                <%= form.text_field :name, class: "form-control", placeholder: "Naam", required: true, autofocus: true %>
                <%= form.label :subject do 'Naam' end %>
            </div>
            <div class="form-floating mt-4">
                <%= form.number_field :slots, class: "form-control", placeholder: "Slots per uur", required: true %>
                <%= form.label :subject do 'Slots per uur' end %>
                <small class="text-muted">Pas dit nooit aan als er al afspraken zijn gemaakt.</small>
            </div>
            <div class="form-floating mt-4">
                <%= form.number_field :minimum, class: "form-control", placeholder: "Minimale aanloop (minuten)", required: true %>
                <%= form.label :subject do 'Minimale aanloop (minuten)' end %>
            </div>
            <div class="form-floating mt-4">
                <%= form.text_area :location, class: "form-control", placeholder: "Standaard locatie", required: true, style: 'height: 5rem;' %>
                <%= form.label :subject do 'Standaard locatie' end %>
            </div>
            <button class="w-100 btn btn-lg btn-primary mt-4" type="submit">Opslaan</button>
        <% end %>
    </div>
</div>

<div class="row justify-content-center pt-5">
    <div class="col-lg-6">
        <h3 class="text-center">Invoer slots</h3>
        <p class="text-center">
            <% @coming_weeks.each do |schedule| %>
            <%= link_to schedule.week.to_s, course_year_week_schedule_path(course_id: @course.id, year_number: schedule.year, week_number: schedule.week) %>
            <% end %>
        </p>
    </div>
</div>

<%= form_with url: course_path(@course) + "/bulk", method: :post do |form| %>
    <div class="row justify-content-center">
        <div class="col-lg-3">
            <div class="form-floating mt-4">
                <%= form.number_field :start, class: "form-control", placeholder: "Eerste week", required: true %>
                <%= form.label :start do 'Eerste week' end %>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="form-floating mt-4">
                <%= form.number_field :end, class: "form-control", placeholder: "Laatste week", required: true %>
                <%= form.label :end do 'Laatste week' end %>
            </div>
        </div>
    </div>

    <div class="row justify-content-center pt-5">
        <div class="col-lg-12">
            <table class="table">
                <tr>
                    <th></th>
                    <th>Zondag</th>
                    <th>Maandag</th>
                    <th>Dinsdag</th>
                    <th>Woensdag</th>
                    <th>Donderdag</th>
                    <th>Vrijdag</th>
                    <th>Zaterdag</th>
                </tr>
                <% for i in 9..17 do %>
                    <tr>
                        <th><%= i %>:00</th>
                        <% for j in 0..6 do %>
                            <td><%= form.number_field j.to_s + "-" + i.to_s, class: "form-control", value: 0, required: true %></td>
                        <% end %>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-lg-6">
            <button class="w-100 btn btn-lg btn-primary mt-4 mb-5" type="submit">Opslaan</button>
        </div>
    </div>
<% end %>

app/views/courses/index.html.erb
<div class="row justify-content-center">
    <div class="col-lg-6">
        <h3 class="text-center">Vakken</h3>
    </div>
</div>

<div class="row justify-content-center pt-3">
    <div class="col-lg-8">
        <table class="table">
            <tr>
                <th>Vak</th>
                <th>Slots per uur</th>
                <th>Aanlooptijd</th>
                <th>Locatie</th>
                <th></th>
            </tr>
            <% @courses.each do |course| %>
                <tr>
                    <td><%= link_to course.name, planner_path(course) %></td>
                    <td><%= course.slots %></td>
                    <td><%= course.minimum %></td>
                    <td><%= course.location %></td>
                    <td><%= link_to "Bewerken", edit_course_path(course) %></td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-lg-6">
        <%= link_to "Nieuw vak", new_course_path, class: "w-100 btn btn-lg btn-primary mt-4" %>
    </div>
</div>

app/views/courses/new.html.erb
<div class="row justify-content-center">
    <div class="col-lg-6">
        <h3 class="text-center">Nieuw vak</h3>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-lg-6">
        <%= form_for [@course] do |form| %>
            <div class="form-floating mt-4">
                <%= form.text_field :name, class: "form-control", placeholder: "Naam", required: true, autofocus: true %>
                <%= form.label :subject do 'Naam' end %>
            </div>
            <div class="form-floating mt-4">
                <%= form.number_field :slots, class: "form-control", placeholder: "Slots per uur", required: true %>
                <%= form.label :subject do 'Slots per uur' end %>
            </div>
            <div class="form-floating mt-4">
                <%= form.number_field :minimum, class: "form-control", placeholder: "Minimale aanloop (minuten)", required: true %>
                <%= form.label :subject do 'Minimale aanloop (minuten)' end %>
            </div>
            <div class="form-floating mt-4">
                <%= form.text_field :location, class: "form-control", placeholder: "Standaard locatie", required: true %>
                <%= form.label :subject do 'Standaard locatie' end %>
            </div>
            <button class="w-100 btn btn-lg btn-primary mt-4" type="submit">Opslaan</button>
        <% end %>
    </div>
</div>

app/views/courses/update.html.erb
<h1>Courses#update</h1>
<p>Find me in app/views/courses/update.html.erb</p>