config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
    # appointment planning for students
    resources 'planner', only: [ :show ]

    # appointments overview for TA's
    resources 'live', only: [ :index ]
    resources 'appointments', param: 'uuid', only: [ :show ] do
        put 'complete'
        put 'claim'
        put 'cancel'
    end

    # change hours etc
    resources 'courses', only: [ :index, :new, :create, :edit, :update ] do
        resources 'appointments', only: [ :create ]
        post 'bulk', to: 'courses#bulk'
        resources 'year', param: 'number', only: [] do
            resources 'week', param: 'number', only: [] do
                resource 'schedule', only: [ :show, :edit, :update ]
            end
        end
        resources 'feeds', only: [ :show ], param: 'token'
    end

    post 'logout', to: 'users#logout'

    # welcome and bumper page
    namespace 'home' do
        get 'index'
        get 'register'
    end

    # user registration
    resources 'users', only: [ :new, :create ]

    root to: "home#index"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :user
    belongs_to :course
    belongs_to :helper, class_name: 'User', optional: true
    delegate :name, to: :helper, prefix: true

    # see https://api.rubyonrails.org/classes/ActiveRecord/Enum.html
    enum status: { active: 0, cancelled: 1, done: 2 }

    after_create_commit  { broadcast_prepend_to 'appointments' }
    after_save do
        case status_previous_change
        in [*, 'cancelled']
            broadcast_remove_to 'appointments'
        in ['active', 'done']
            broadcast_replace_to 'appointments'
        else
        end
    end

    scope :all_remaining_for_today, -> do
        date = Date.today
        where(day: date.wday, week: date.cweek, year: date.year).
        where(status: [:active]).
        where("hour >= ?", DateTime.now.hour-1)
    end

    scope :grouped_by_start_time, -> do
        group_by(&:starting_time).
        sort {|a,b| a[0] <=> b[0]}
    end
    
    scope :ordered_by_start_time, -> do
        sort_by { |a| a.starting_time }
    end

    def starting_time
        # exactly the library function we need
        CommercialTime.create(year, week, day, hour, (slot-1).to_f/course.slots*60)
    end

    def formatted_starting_time(format=:datetime)
        case format
        when :time
            starting_time.strftime '%-H:%M'
        when :datetime
            starting_time.strftime '%A %-d %B %Y, %-H:%M'
        end
    end

    def self.booked_per_slot(year, week, day)
        where(year: year, week: week, day: day, status: :active).group(:hour, :slot).count
    end

    def to_param
        uuid
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :require_user
    before_action :require_assistant, only: [ :complete, :claim ]

    def show
        @appointment = Appointment.find_by_uuid params[:uuid]
    end

    def cancel
        appointment = Appointment.find_by_uuid params[:appointment_uuid]
        appointment.status = 1
        appointment.save!
        redirect_back fallback_location: '/'
    end

    def complete
        appointment = Appointment.find_by_uuid params[:appointment_uuid]
        appointment.status = 2
        appointment.save!
        redirect_back fallback_location: '/'
    end

    def claim
        appointment = Appointment.find_by uuid:params[:appointment_uuid], helper:nil
        if appointment.present? && appointment.update(helper: current_user)
            redirect_back fallback_location: '/', notice: "Yes, go ahead!"
        else
            redirect_back fallback_location: '/', alert: "Someone already claimed this!"
        end
    end

    def create
        course = Course.find params[:course_id]
        date = Time.at(filter_params[:slot].to_i).to_datetime

        # catch nonsensical times
        if filter_params[:slot].to_i < 1
            raise ActionController::RoutingError.new('Invalid Time')
        end

        slot = date.min / (60/4) + 1
        hour = date.hour
        day = date.wday
        week = date.cweek
        year = date.year

        # check if this choice is available, or find next slot
        best_match_hour, best_match_slot =
            course.first_available_slot_starting_from year, week, day, hour, slot

        # in case radio buttons are offered for the location,
        # user-entered location will be in the :other_location field
        location =
            filter_params[:location] == "Other" && params[:other_location] ||
            filter_params[:location]

        # anything's still available for chosen day?
        if best_match_hour
            @a = Appointment.create! user: current_user,
                                     course: course,
                                     slot: best_match_slot,
                                     hour: best_match_hour,
                                     day: day,
                                     week: week,
                                     year: year,
                                     subject: filter_params[:subject],
                                     location: location,
                                     uuid: Digest::UUID.uuid_v4

            AppointmentMailer.with(appointment: @a).confirmation_mail.deliver_later
            redirect_to @a, notice: "Your appointment was made!"
        else
            redirect_to planner_path(course),
                alert: "Unfortunately, timeslots are full for the day. Please select a new time below."
        end
    end

    def filter_params
        params.require(:appointment).permit(:slot, :subject, :location)
    end
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>" class="col-lg-3 col-md-6 mt-0 mb-4 live-col" data-appointment="<%= appointment.id %>" data-sort-code="<%= appointment.starting_time.strftime("%H%M") %><%= appointment.created_at.to_i %>">
    <%= appointment.starting_time.to_fs(:time) %>
    <div class="card <%= appointment.status %>">
        <div class="card-body">
            <small class="text-uppercase text-muted"><%= appointment.course.name %></small>
            <h6 class="card-title mt-0 mt-sm-1 mb-0"><%= appointment.user.name %></h6>
            <p class="mt-0 text-truncate small">@ <%= link_to_if appointment.location =~ URI.regexp, appointment.location, appointment.location %></p>
            <p class="mt-0 mt-md-2 mb-0">"<%= appointment.subject %>"</p>
        </div>
        <div class="card-footer d-flex flex-row justify-content-end align-items-center">
                <% if appointment.cancelled? %>
                    <span class="text-muted">Cancelled</span>
                <% end %>
                <% if appointment.helper.present? %>
                    <%= appointment.helper_name %>
                    <% unless appointment.done? %>
                    <%= button_to '✔️ Done', appointment_complete_path(appointment), method: :put, class: 'ms-3 btn btn-primary btn-sm float-end', form_class: 'd-inline-block' %>
                    <% end %>
                <% elsif appointment.active? %>
                    <%= button_to 'Me', appointment_claim_path(appointment), method: :put, class: 'ms-3 btn btn-primary btn-sm float-end', form_class: 'd-inline-block' %>
                <% end %>
        </div>
    </div>
</div>

app/views/appointments/create.html.erb
<div class="row justify-content-center">
    <div class="col-lg-6">
        <h1 class="text-center mt-5">Your appointment is set! 🥳</h3>
        <h5 class="text-center text-muted fw-light mt-5">We've sent you an e-mail to confirm.</h5>
        <h5 class="text-center strong mt-5">Note: your appointment was set at <u><%= @a.formatted_starting_time :time %></u></h5>
    </div>
</div>

app/views/appointments/show.html.erb
<div class="row justify-content-center">
    <div class="col-lg-6">
        <h2>📅 Appointment</h2>

        <% unless @appointment.cancelled? %>
        <p class="mt-4">
            Your appointment
            <% if @appointment.active? %>
            will take
            <% else %>
            took
            <% end %>
            place on <strong><%= @appointment.formatted_starting_time %></strong>.
        </p>
        <p>
            Location: <strong><%= @appointment.location %></strong>
        </p>
        <% else %>
        <p class="mt-4">
            Your appointment was <strong>cancelled</strong>. It was formerly planned at <%= @appointment.formatted_starting_time %>.
        </p>
        <% end %>

        <% if @appointment.active? %>
        <p>
            <%= button_to '🗑 Cancel Now', appointment_cancel_path(@appointment), method: :put, onclick: 'return confirm("Really cancel?");', class: 'btn btn-primary', form_class: 'd-inline-block' %>
        </p>
        <% end %>
    </div>
</div>